server:
    errors:
        not_found:
            code: A1
            message: Student does't exist
            httpStatus: 404
        already_exist:
            code: B2
            message: Student Already Exists
            httpStatus: 409
        database_error:
            code: C3
            message : Database Error
            httpStatus: 500